"""initial schema with investment tables

Revision ID: 1d436ec8dc62
Revises: 
Create Date: 2026-04-28 11:06:55.640725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d436ec8dc62'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_tag_overrides',
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('tag', sa.String(length=50), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('category')
    )
    op.create_table('goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('target_amount', sa.Float(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('current_amount', sa.Float(), nullable=True),
    sa.Column('monthly_sip', sa.Float(), nullable=True),
    sa.Column('linked_isin', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('holdings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('instrument_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=True),
    sa.Column('isin', sa.String(length=20), nullable=True),
    sa.Column('folio_number', sa.String(length=100), nullable=True),
    sa.Column('units', sa.Float(), nullable=True),
    sa.Column('avg_cost_per_unit', sa.Float(), nullable=True),
    sa.Column('current_price', sa.Float(), nullable=True),
    sa.Column('current_value', sa.Float(), nullable=True),
    sa.Column('invested_value', sa.Float(), nullable=True),
    sa.Column('unrealised_pnl', sa.Float(), nullable=True),
    sa.Column('unrealised_pnl_pct', sa.Float(), nullable=True),
    sa.Column('account', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_date', 'name', 'account', name='uq_holding_snapshot')
    )
    op.create_index(op.f('ix_holdings_snapshot_date'), 'holdings', ['snapshot_date'], unique=False)
    op.create_table('investments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('instrument_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=True),
    sa.Column('isin', sa.String(length=20), nullable=True),
    sa.Column('folio_number', sa.String(length=100), nullable=True),
    sa.Column('units', sa.Float(), nullable=True),
    sa.Column('price_per_unit', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('transaction_type', sa.String(length=20), nullable=True),
    sa.Column('account', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'name', 'amount', 'transaction_type', 'account', name='uq_investment')
    )
    op.create_index(op.f('ix_investments_date'), 'investments', ['date'], unique=False)
    op.create_index(op.f('ix_investments_month'), 'investments', ['month'], unique=False)
    op.create_table('liabilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('liability_type', sa.String(length=50), nullable=True),
    sa.Column('principal', sa.Float(), nullable=True),
    sa.Column('outstanding', sa.Float(), nullable=False),
    sa.Column('interest_rate', sa.Float(), nullable=True),
    sa.Column('emi_amount', sa.Float(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('account', sa.String(length=100), nullable=True),
    sa.Column('as_of_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'as_of_date', name='uq_liability')
    )
    # SQLite can't DROP CONSTRAINT directly — use batch mode (copy-and-move)
    with op.batch_alter_table('transactions', recreate='auto') as batch_op:
        batch_op.drop_constraint('uq_transaction', type_='unique')
        batch_op.create_unique_constraint('uq_transaction', ['date', 'amount', 'description', 'account'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', recreate='auto') as batch_op:
        batch_op.drop_constraint('uq_transaction', type_='unique')
        batch_op.create_unique_constraint('uq_transaction', ['date', 'amount', 'description'])
    op.drop_table('liabilities')
    op.drop_index(op.f('ix_investments_month'), table_name='investments')
    op.drop_index(op.f('ix_investments_date'), table_name='investments')
    op.drop_table('investments')
    op.drop_index(op.f('ix_holdings_snapshot_date'), table_name='holdings')
    op.drop_table('holdings')
    op.drop_table('goals')
    op.drop_table('category_tag_overrides')
    # ### end Alembic commands ###
